version: '3.3'

services:
  postgres:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: terceira_fase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - "./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql"