
spring:
  application:
    name: '@project.name@'
    client: senac
    version: '@project.version@'
    description: '@project.description@'
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true
  profiles:
    group:
      - dev
      - hml
      - prd
    active: ${ECS_ENVIRONMENT:dev}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?ApplicationName=br-senac-terceira-fase-alocacao
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      poolName: Hikari
      auto-commit: false
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 20000
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
        default_schema: public
        id.new_generator_mappings: true
        connection.provider_disables_autocommit: true
        cache.use_second_level_cache: false
        cache.use_query_cache: false
        generate_statistics: false
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

  task:
    execution:
      thread-name-prefix: br-senac-terceira-fase-alocacao-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000


server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
  http2:
    enabled: true
  servlet:
    context-path: ${CONTEXT_PATH:/api/v1}
    session:
      timeout: 3600s
  port: ${SERVER_PORT:9092}


logging:
  level:
    ROOT: INFO
    br.com.serasa: INFO